FROM node:14 as build-stage
WORKDIR /.
COPY . .

FROM nginx:stable
COPY --from=build-stage source-folder destination-folder
COPY nginx/nginx.fileserver.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
